export { default as ProjectCard } from "@/app/projects/[slug]/components/ProjectCard";
export { default as ProjectGrid } from "@/app/projects/[slug]/components/ProjectGrid";
export { default as ProjectImage } from "@/app/projects/[slug]/components/ProjectImage";
export { default as ProjectNav } from "@/app/projects/[slug]/components/ProjectNav";
export { default as ProjectStack } from "@/app/projects/[slug]/components/ProjectStack";
export { default as Tabs } from "@/app/projects/[slug]/components/Tabs";
export { default as TabsList } from "@/app/projects/[slug]/components/TabsList";
export { default as TabsPanel } from "@/app/projects/[slug]/components/TabsPanel";
export { default as TabsTrigger } from "@/app/projects/[slug]/components/TabsTrigger";
